version: '3.8'

services:
  mariadb:
    image: mariadb:11
    container_name: nsu-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nsudb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/02-data.sql
    networks:
      - nsu-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: nsu-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - nsu-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: nsu-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://nsu-kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - nsu-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nsu-app
    depends_on:
      - mariadb
      - kafka
    ports:
      - "8080:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: nsu-kafka:9092
      SPRING_DATASOURCE_URL: jdbc:mariadb://nsu-mariadb:3306/nsudb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    networks:
      - nsu-network

volumes:
  mariadb-data:

networks:
  nsu-network:
    driver: bridge